glyphs:
  vault:
    # - type: randomSecret
    #   name: keycloak-access
    - type: secret
      name: keycloak-access
      format: plain
      labels:
        sarasa: esta
      staticData:
        username: keycloak
      randomKey: key.complex
      serviceAccount: sarasa
      random: true
    - type: prolicy
      name: sarsa
      serviceAccount: pedro