apiVersion: v2
name: summon
version: 1.0.0
description: the summon chart of kast to create microservices or run conainers
home: https://github.com/kast-spells
sources:
  - https://github.com/kast-spells/kast-system
maintainers:
  - name: namen malkav
    email: namenmalkav@gmail.com
  - name: laaledesiempre
    email: laaledesiempre@disroot.org